insales:
  app_api_key: 'moysklad-app'
  app_secret: 'secret'

active_record_encryption:
  primary_key: K23JN4DEHEvLqxEPiRQzHVwdCfouAN4x
  deterministic_key: KsdkFgQeyJMA0uB1vmNxUdfFMVDmss8c
  key_derivation_salt: BXHiozEk7Q7dUFpF2z4WsXx1HlLHaxlB

secret_key_base: 'secret'